---
title: "Formatting NRS tables"
author: "Dave"
format: html
editor: visual
---

## Libraries

```{r libraries}
library(fs)
library(here)
library(vroom)
library(purrr)
library(stringr)
library(janitor)
library(dplyr)
```

## Read tables

```{r read_tables}
paths <-
  dir_ls(here("nrs-tables"))

paths <-
  set_names(paths, 
            path_ext_remove(paths) |> 
              str_remove("(?<=^).+_") |> 
              str_replace_all("-", "_"))

paths

tables <-
  map(paths, \(x) vroom(x, skip = 4, show_col_types = FALSE,
                        guess_max = Inf)) |> 
  map(\(x) rename(x, oa_code_2021 = 1)) |> 
  map(clean_names)
```

## Drop 'all people' col

```{r drop_all_people}
tables <- map(tables, \(x) select(x, -any_of("all_people")))
```

## Rename

```{r rename}
tables$age_by_single_year <- 
  rename_with(
    tables$age_by_single_year, 
    \(nm) str_replace(nm, "x", "age_"),
    -1
  ) |> 
  rename(age_under_1 = under_1)
```

## Reformat

```{r reformat}
tables <- 
  map(tables, 
    \(x){
      mutate(x, across(-1,
                       \(y){
                         replace(y, y == "-", "0") |>
                           as.numeric()
                         }))
      })
```

## Tidy untidy data

```{r tidy_untidy}
ethnic_group_tmp <- tables$ethnic_group

tables$ethnic_group <- 
  select(tables$ethnic_group, !ends_with("_total"))

tables$ethnic_group_grouped <- 
  select(ethnic_group_tmp, oa_code_2021, ends_with("_total"))
```

## Save

```{r save}
dir_create(here("data"))

saveRDS(tables, here("data", "output-01_cleaned-tables.RDS"))
```
