---
title: "Make 5 year age"
author: "Dave"
format: html
editor: visual
---

## Libraries

```{r libraries}
library(fs)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
```

## Read data

```{r read_data}
tables <- readRDS(here("data", "output-01_cleaned-tables.RDS"))
```

## Make five year age table

Pivot age long:

```{r make_five_year_age}
long_age <- pivot_longer(tables$age_by_single_year, -1)
head(long_age)
```

Extract year as number:

```{r extract_year}
long_age <- mutate(long_age,
                   num = parse_number(name),
                   num = {num[1] <- 0; num})
```

Group age:

```{r group_age}
long_age <- mutate(long_age, age_band = floor(num/5))

labels <- 
  select(long_age, age_band) |> 
  distinct() |> 
  mutate(label = str_c(age_band * 5,
                       age_band * 5 + 4, 
                       sep = "_"))


long_age <- 
  left_join(long_age, labels, by = "age_band") |> 
  select(oa_code_2021, label, value) |> 
  summarise(value = sum(value), .by = c(oa_code_2021, label))
```

Pivot wider:

```{r pivot_wider}
age_five_year <- 
  mutate(long_age, label = str_c("age_", label)) |> 
  pivot_wider(names_from = label, id_cols = oa_code_2021)

age_five_year <- rename(age_five_year, age_100_plus = age_100_104)
```

## Save

```{r save}
tables$age_five_year <- age_five_year

saveRDS(tables, here("data", "output-02_five-year-age-added.RDS"))
```
